### ISSUE TITLE
Improve modularity of code base

### ISSUE THREAD

**Issue by mwakok** [SATAY-LL/LaanLab-SATAY-DataAnalysis#52]
**Observations**
- Code base contains some modularity, but scripts contain many functionalities (#51)
- Non-modular code is difficult to maintain and test

**Proposed solution**
- [ ] Refactor each python script and put its functionalities in a separate functions

**Requirements**
- [x] Improve branch managenemt (#48)
- [x] Write down tasks of the script (#51)
- [x] Improve project organisation (#49)
- [x] Create first integration tests
